# Normal configuration
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['CYPRESS'] ? 'url_shortener_test' : 'url_shortener_development' %>

test:
  <<: *default
  database: url_shortener_test

production:
  <<: *default
  database: url_shortener_roduction
  username: url_shortener_
  password: <%= ENV['URL_SHORTENER_DATABASE_PASSWORD'] %>


# Docker configuration
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   database: <%= ENV['DATABASE_NAME'] %>
#   username: <%= ENV['DATABASE_USER'] %>
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   port: <%= ENV['DATABASE_PORT'] || '5432' %>
#   host: <%= ENV['DATABASE_HOST'] %>
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000


# development:
#   <<: *default

# test:
#   <<: *default

# production:
#   <<: *default
